### ISSUE TITLE
4쇄 책 코드와 다른데요. 수정은 이제 안해주시나요.

### ISSUE THREAD

**Issue by alisol** [pystockhub/book#1]
2017년 코드라서 

2019년 4쇄에 실린 코드와 다른 것 같아요.

**Comment by mr-yoo** [comment]
1차적으로 업데이트 했는데요.
혹시 빠트린 부분이 있을 수 있으니, 다른 부분을 알려주시면 바로 업데이트 하겠습니다.

피드백 감사합니다.

**Comment by psjmessage** [comment]
ch14. 02.py가 책이랑 다르네요

**Comment by mr-yoo** [comment]
ch14.02.py는 책과 같아서요. 조금 더 구체적으로 이야기 해주시면 확인해 보겠습니다.
![image](https://user-images.githubusercontent.com/29349211/68026171-369c2a00-fcf2-11e9-81de-09f82905c74e.png)

**Comment by psjmessage** [comment]
제가 구매한 책에는 아래 코드로 되어 있네요 (page 378)

import pandas_datareader.data as web
import fix_yahoo_finance as yf
import matplotlib.pyplot as plt
from zipline.api import order, symbol
from zipline. algorithm import TradingAlgorithm

yf.pdr_override()
data = web.get_data_yahoo("AAPL", start="2010-01-01", end="2019-01-01")

data = data[['Close']]
data.columns = ["AAPL"]
data = data.tz_localize('UTC')

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('AAPL'), 1)

algo = TradingAlgorithm(initialize=initialize, handle_data=handle_data)
result = algo.run(data)

plt.plot(result.index, result.portfolio_value)
plt.show()

**Comment by mr-yoo** [comment]
우선 불편을 드려 죄송합니다. 지적하신 것과 같이 wikidocs와 github는 동일한데 인쇄 버전과는 다릅니다.  zipline이 높아진 python 버전을 지원하지 않아 많은 의존성 문제를 일으키고 있습니다. 책도 대규모 수정이 필요해서 현재 zipline의 업데이트를 하지 못하고 있어요. 가까운 시일에 업데이트를 해보도록 할게요.

**Comment by minsuk-sung** [comment]
ch10/12.py 코드 실습중입니다. 이 부분에 대한 에러도 버전 문제인가요?
```
Traceback (most recent call last):
  File "c:/Users/mssun/trading-system/ch10/12.py", line 15, in <module>        
    instStockChart.BlockRequest()
  File "<COMObject CpSysDib.StockChart>", line 2, in BlockRequest
pywintypes.com_error: (-2147352567, '예외가 발생했습니다.', (0, None, 'U-CYBOS 
가 서버에 접속되어 있지 않습니다.', None, 0, -2147483638), None)
```
